#ifndef __ITEMPOOL_H__
#define __ITEMPOOL_H__

using namespace std;

/*
    'Item' covers both release NPCs and actual items
    Flags tracked per item can tell what it actually is
    126 item locations + 170 NPCs puts an upper bound on
    how many things we would ever need to list
*/
#define MAX_POOL_SIZE 300
#define ITEM_NAME_MAX_LENGTH 40
#define NPC_ID_MAX 420


/*
    This gets written to chest or NPC/tile script data to specify item.
*/
enum class ItemId : unsigned char {
    NOTHING         = 0x00,
    SWORD_OF_LIFE   = 0x01,
    PSYCHO_SWORD    = 0x02,
    CRITICAL_SWORD  = 0x03,
    LUCKY_BLADE     = 0x04,
    ZANTETSU_SWORD  = 0x05,
    SPIRIT_SWORD    = 0x06,
    RECOVERY_SWORD  = 0x07,
    SOUL_BLADE      = 0x08,
    IRON_ARMOR      = 0x09,
    ICE_ARMOR       = 0x0A,
    BUBBLE_ARMOR    = 0x0B,
    MAGIC_ARMOR     = 0x0C,
    MYSTIC_ARMOR    = 0x0D,
    LIGHT_ARMOR     = 0x0E,
    ELEMENTAL_MAIL  = 0x0F,
    SOUL_ARMOR      = 0x10,
    FLAME_BALL      = 0x11,
    LIGHT_ARROW     = 0x12,
    MAGIC_FLARE     = 0x13,
    ROTATOR         = 0x14,
    SPARK_BOMB      = 0x15,
    FLAME_PILLAR    = 0x16,
    TORNADO         = 0x17,
    PHOENIX         = 0x18,
    GOATS_FOOD      = 0x19,
    HARP_STRING     = 0x1A,
    PASS            = 0x1B,
    DREAM_ROD       = 0x1C,
    LEOS_BRUSH      = 0x1D,
    GREENWOOD_LEAF  = 0x1E,
    MOLES_RIBBON    = 0x1F,
    BIG_PEARL       = 0x20,
    MERMAIDS_TEARS  = 0x21,
    MUSHROOM_SHOES  = 0x22,
    MOBILE_KEY      = 0x23,
    THUNDER_RING    = 0x24,
    DELICIOUS_SEEDS = 0x25,
    ACTINIDIA_LEAF  = 0x26,
    DOOR_KEY        = 0x27,
    PLATINUM_CARD   = 0x28,
    VIP_CARD        = 0x29,
    EMBLEM_A        = 0x2A,
    EMBLEM_B        = 0x2B,
    EMBLEM_C        = 0x2C,
    EMBLEM_D        = 0x2D,
    EMBLEM_E        = 0x2E,
    EMBLEM_F        = 0x2F,
    EMBLEM_G        = 0x30,
    EMBLEM_H        = 0x31,
    RED_HOT_MIRROR  = 0x32,
    RED_HOT_BALL    = 0x33,
    RED_HOT_STICK   = 0x34,
    POWER_BRACELET  = 0x35,
    SHIELD_BRACELET = 0x36,
    SUPER_BRACELET  = 0x37,
    MEDICAL_HERB    = 0x38,
    STRANGE_BOTTLE  = 0x39,
    BROWN_STONE     = 0x3A,
    GREEN_STONE     = 0x3B,
    BLUE_STONE      = 0x3C,
    SILVER_STONE    = 0x3D,
    PURPLE_STONE    = 0x3E,
    BLACK_STONE     = 0x3F,
    MAGIC_BELL      = 0x40,
    GEMS_EXP        = 0xFF,
};

/*
    This is the offset into the lair list for the NPC released.
    We need this to put together the randomized lair data.
*/
enum class NpcId : unsigned int {
    NPC_OLD_WOMAN                     = 2,
    NPC_TOOL_SHOP_OWNER               = 6,
    NPC_TULIP                         = 7,
    NPC_BRIDGE_GUARD                  = 8,
    NPC_VILLAGE_CHIEF                 = 9,
    NPC_IVY_CHEST_ROOM                = 13,
    NPC_WATER_MILL                    = 14,
    NPC_GOAT_HERB                     = 15,
    NPC_LISA                          = 16,
    NPC_TULIP2                        = 17,
    NPC_ARCHITECT                     = 18,
    NPC_IVY                           = 19,
    NPC_GOAT                          = 21,
    NPC_TEDDY                         = 22,
    NPC_TULIP3                        = 24,
    NPC_LEOS_HOUSE                    = 26,
    NPC_LONELY_GOAT                   = 29,
    NPC_TULIP_PASS                    = 34,
    NPC_BOY_CABIN                     = 35,
    NPC_BOY_CAVE                      = 37,
    NPC_OLD_MAN                       = 40,
    NPC_OLD_MAN2                      = 41,
    NPC_IVY2                          = 42,
    NPC_IVY_EMBLEM_A                  = 43,
    NPC_IVY_RECOVERY_SWORD            = 44,
    NPC_TULIP4                        = 46,
    NPC_GOAT2                         = 47,
    NPC_BIRD_RED_HOT_MIRROR           = 55,
    NPC_BIRD                          = 56,
    NPC_DOG                           = 60,
    NPC_DOG2                          = 61,
    NPC_DOG3                          = 63,
    NPC_MOLE_SHIELD_BRACELET          = 64,
    NPC_SQUIRREL_EMBLEM_C             = 65,
    NPC_SQUIRREL_PSYCHO_SWORD         = 67,
    NPC_BIRD2                         = 70,
    NPC_MOLE_SOUL_OF_LIGHT            = 73,
    NPC_DEER                          = 74,
    NPC_CROCODILE                     = 78,
    NPC_SQUIRREL                      = 79,
    NPC_GREENWOODS_GUARDIAN           = 80,
    NPC_MOLE                          = 81,
    NPC_DOG4                          = 86,
    NPC_SQUIRREL_ICE_ARMOR            = 88,
    NPC_SQUIRREL2                     = 89,
    NPC_DOG5                          = 90,
    NPC_CROCODILE2                    = 91,
    NPC_MOLE2                         = 92,
    NPC_SQUIRREL3                     = 93,
    NPC_BIRD_GREENWOOD_LEAF           = 97,
    NPC_MOLE3                         = 98,
    NPC_DEER_MAGIC_BELL               = 99,
    NPC_BIRD3                         = 100,
    NPC_CROCODILE3                    = 111,
    NPC_MONMO                         = 114,
    NPC_DOLPHIN                       = 124,
    NPC_ANGELFISH                     = 131,
    NPC_MERMAID                       = 132,
    NPC_ANGELFISH2                    = 134,
    NPC_MERMAID_PEARL                 = 138,
    NPC_MERMAID2                      = 139,
    NPC_DOLPHIN_SAVES_LUE             = 140,
    NPC_MERMAID_STATUE_BLESTER        = 141,
    NPC_MERMAID_RED_HOT_STICK         = 142,
    NPC_LUE                           = 143,
    NPC_MERMAID3                      = 146,
    NPC_MERMAID_NANA                  = 149,
    NPC_MERMAID4                      = 153,
    NPC_DOLPHIN2                      = 155,
    NPC_MERMAID_STATUE_ROCKBIRD       = 157,
    NPC_MERMAID_BUBBLE_ARMOR          = 161,
    NPC_MERMAID5                      = 164,
    NPC_MERMAID6                      = 165,
    NPC_MERMAID_TEARS                 = 167,
    NPC_MERMAID_STATUE_DUREAN         = 171,
    NPC_ANGELFISH3                    = 173,
    NPC_ANGELFISH_SOUL_OF_SHIELD      = 177,
    NPC_MERMAID_MAGIC_FLARE           = 181,
    NPC_MERMAID_QUEEN                 = 182,
    NPC_MERMAID_STATUE_GHOST_SHIP     = 185,
    NPC_DOLPHIN_SECRET_CAVE           = 187,
    NPC_MERMAID7                      = 189,
    NPC_ANGELFISH4                    = 190,
    NPC_MERMAID8                      = 192,
    NPC_DOLPHIN_PEARL                 = 193,
    NPC_MERMAID9                      = 194,
    NPC_GRANDPA                       = 201,
    NPC_GIRL                          = 202,
    NPC_MUSHROOM                      = 203,
    NPC_BOY                           = 204,
    NPC_GRANDPA2                      = 211,
    NPC_SNAIL_JOCKEY                  = 212,
    NPC_NOME                          = 214,
    NPC_BOY2                          = 215,
    NPC_MUSHROOM_EMBLEM_F             = 221,
    NPC_DANCING_GRANDMA               = 225,
    NPC_DANCING_GRANDMA2              = 230,
    NPC_SNAIL_EMBLEM_E                = 232,
    NPC_BOY_MUSHROOM_SHOES            = 233,
    NPC_GRANDMA                       = 234,
    NPC_GIRL2                         = 235,
    NPC_MUSHROOM2                     = 238,
    NPC_SNAIL_RACER                   = 239,
    NPC_SNAIL_RACER2                  = 240,
    NPC_GIRL3                         = 242,
    NPC_MUSHROOM3                     = 246,
    NPC_SNAIL                         = 247,
    NPC_GRANDPA3                      = 248,
    NPC_SNAIL2                        = 250,
    NPC_GRANDPA4                      = 252,
    NPC_GRANDPA_LUNE                  = 254,
    NPC_GRANDPA5                      = 255,
    NPC_MOUNTAIN_KING                 = 259,
    NPC_PLANT_HERB                    = 265,
    NPC_PLANT                         = 267,
    NPC_CHEST_OF_DRAWERS_MYSTIC_ARMOR = 268,
    NPC_CAT                           = 269,
    NPC_GREAT_DOOR_ZANTETSU_SWORD     = 274,
    NPC_CAT2                          = 276,
    NPC_GREAT_DOOR                    = 282,
    NPC_CAT3                          = 283,
    NPC_MODEL_TOWN1                   = 286,
    NPC_GREAT_DOOR_MODEL_TOWNS        = 288,
    NPC_STEPS_UPSTAIRS                = 290,
    NPC_CAT_DOOR_KEY                  = 294,
    NPC_MOUSE                         = 297,
    NPC_MARIE                         = 303,
    NPC_DOLL                          = 310,
    NPC_CHEST_OF_DRAWERS              = 311,
    NPC_PLANT2                        = 313,
    NPC_MOUSE2                        = 315,
    NPC_MOUSE_SPARK_BOMB              = 316,
    NPC_MOUSE3                        = 318,
    NPC_GREAT_DOOR_SOUL_OF_DETECTION  = 322,
    NPC_MODEL_TOWN2                   = 325,
    NPC_MOUSE4                        = 330,
    NPC_STEPS_MARIE                   = 331,
    NPC_CHEST_OF_DRAWERS2             = 332,
    NPC_PLANT_ACTINIDIA_LEAVES        = 333,
    NPC_MOUSE5                        = 338,
    NPC_CAT4                          = 339,
    NPC_STAIRS_POWER_PLANT            = 341,
    NPC_SOLDIER                       = 345,
    NPC_SOLDIER2                      = 346,
    NPC_SOLDIER3                      = 351,
    NPC_SOLDIER_ELEMENTAL_MAIL        = 353,
    NPC_SOLDIER4                      = 354,
    NPC_SOLDIER5                      = 358,
    NPC_SINGER_CONCERT_HALL           = 359,
    NPC_SOLDIER6                      = 360,
    NPC_MAID                          = 363,
    NPC_SOLDIER_LEFT_TOWER            = 365,
    NPC_SOLDIER_DOK                   = 366,
    NPC_SOLDIER_PLATINUM_CARD         = 368,
    NPC_SINGER                        = 370,
    NPC_SOLDIER_SOUL_OF_REALITY       = 377,
    NPC_MAID2                         = 382,
    NPC_QUEEN_MAGRIDD                 = 383,
    NPC_SOLDIER_WITH_LEO              = 385,
    NPC_SOLDIER_RIGHT_TOWER           = 386,
    NPC_DR_LEO                        = 387,
    NPC_SOLDIER7                      = 389,
    NPC_SOLDIER8                      = 390,
    NPC_MAID_HERB                     = 391,
    NPC_SOLDIER_CASTLE                = 396,
    NPC_SOLDIER9                      = 397,
    NPC_SOLDIER10                     = 399,
    NPC_SOLDIER11                     = 402,
    NPC_KING_MAGRIDD                  = 405,
};

/*
    This is a purely artificial index into a list of all Items
    that we can use to refer to ItemPool entries
*/
enum class ItemIndex : unsigned int {
    NOTHING = 0,
    SWORD_OF_LIFE,
    PSYCHO_SWORD,
    CRITICAL_SWORD,
    LUCKY_BLADE,
    ZANTETSU_SWORD,
    SPIRIT_SWORD,
    RECOVERY_SWORD,
    SOUL_BLADE,
    IRON_ARMOR,
    ICE_ARMOR,
    BUBBLE_ARMOR,
    MAGIC_ARMOR,
    MYSTIC_ARMOR,
    LIGHT_ARMOR,
    ELEMENTAL_MAIL,
    SOUL_ARMOR,
    FLAME_BALL,
    LIGHT_ARROW,
    MAGIC_FLARE,
    ROTATOR,
    SPARK_BOMB,
    FLAME_PILLAR,
    TORNADO,
    PHOENIX,
    GOATS_FOOD,
    HARP_STRING,
    PASS,
    DREAM_ROD,
    LEOS_BRUSH,
    GREENWOOD_LEAF,
    MOLES_RIBBON,
    BIG_PEARL,
    MERMAIDS_TEARS,
    MUSHROOM_SHOES,
    MOBILE_KEY,
    THUNDER_RING,
    DELICIOUS_SEEDS,
    ACTINIDIA_LEAF,
    DOOR_KEY,
    PLATINUM_CARD,
    VIP_CARD,
    EMBLEM_A,
    EMBLEM_B,
    EMBLEM_C,
    EMBLEM_D,
    EMBLEM_E,
    EMBLEM_F,
    EMBLEM_G,
    EMBLEM_H,
    RED_HOT_MIRROR,
    RED_HOT_BALL,
    RED_HOT_STICK,
    POWER_BRACELET,
    SHIELD_BRACELET,
    SUPER_BRACELET,
    MEDICAL_HERB,
    STRANGE_BOTTLE,
    BROWN_STONE,
    GREEN_STONE,
    BLUE_STONE,
    SILVER_STONE,
    PURPLE_STONE,
    BLACK_STONE,
    MAGIC_BELL,

    GEMS_EXP_1,
    GEMS_EXP_12,
    GEMS_EXP_30,
    GEMS_EXP_40,
    GEMS_EXP_50,
    GEMS_EXP_60,
    GEMS_EXP_80,
    GEMS_EXP_100,
    GEMS_EXP_150,
    GEMS_EXP_180,
    GEMS_EXP_200,
    GEMS_EXP_250,
    GEMS_EXP_300,
    GEMS_EXP_400,

    NPC_OLD_WOMAN,
    NPC_TOOL_SHOP_OWNER,
    NPC_TULIP,
    NPC_BRIDGE_GUARD,
    NPC_VILLAGE_CHIEF,
    NPC_IVY_CHEST_ROOM,
    NPC_WATER_MILL,
    NPC_GOAT_HERB,
    NPC_LISA,
    NPC_TULIP2,
    NPC_ARCHITECT,
    NPC_IVY,
    NPC_GOAT,
    NPC_TEDDY,
    NPC_TULIP3,
    NPC_LEOS_HOUSE,
    NPC_LONELY_GOAT,
    NPC_TULIP_PASS,
    NPC_BOY_CABIN,
    NPC_BOY_CAVE,
    NPC_OLD_MAN,
    NPC_OLD_MAN2,
    NPC_IVY2,
    NPC_IVY_EMBLEM_A,
    NPC_IVY_RECOVERY_SWORD,
    NPC_TULIP4,
    NPC_GOAT2,

    NPC_BIRD_RED_HOT_MIRROR,
    NPC_BIRD,
    NPC_DOG,
    NPC_DOG2,
    NPC_DOG3,
    NPC_MOLE_SHIELD_BRACELET,
    NPC_SQUIRREL_EMBLEM_C,
    NPC_SQUIRREL_PSYCHO_SWORD,
    NPC_BIRD2,
    NPC_MOLE_SOUL_OF_LIGHT,
    NPC_DEER,
    NPC_CROCODILE,
    NPC_SQUIRREL,
    NPC_GREENWOODS_GUARDIAN,
    NPC_MOLE,
    NPC_DOG4,
    NPC_SQUIRREL_ICE_ARMOR,
    NPC_SQUIRREL2,
    NPC_DOG5,
    NPC_CROCODILE2,
    NPC_MOLE2,
    NPC_SQUIRREL3,
    NPC_BIRD_GREENWOOD_LEAF,
    NPC_MOLE3,
    NPC_DEER_MAGIC_BELL,
    NPC_BIRD3,
    NPC_CROCODILE3,
    NPC_MONMO,

    NPC_DOLPHIN,
    NPC_ANGELFISH,
    NPC_MERMAID,
    NPC_ANGELFISH2,
    NPC_MERMAID_PEARL,
    NPC_MERMAID2,
    NPC_DOLPHIN_SAVES_LUE,
    NPC_MERMAID_STATUE_BLESTER,
    NPC_MERMAID_RED_HOT_STICK,
    NPC_LUE,
    NPC_MERMAID3,
    NPC_MERMAID_NANA,
    NPC_MERMAID4, // Opens NW platform, alternative path to left side of St Elles
    NPC_DOLPHIN2,
    NPC_MERMAID_STATUE_ROCKBIRD,
    NPC_MERMAID_BUBBLE_ARMOR,
    NPC_MERMAID5,
    NPC_MERMAID6,
    NPC_MERMAID_TEARS,
    NPC_MERMAID_STATUE_DUREAN,
    NPC_ANGELFISH3,
    NPC_ANGELFISH_SOUL_OF_SHIELD,
    NPC_MERMAID_MAGIC_FLARE,
    NPC_MERMAID_QUEEN,
    NPC_MERMAID_STATUE_GHOST_SHIP,
    NPC_DOLPHIN_SECRET_CAVE,
    NPC_MERMAID7,
    NPC_ANGELFISH4,
    NPC_MERMAID8,
    NPC_DOLPHIN_PEARL,
    NPC_MERMAID9,

    NPC_GRANDPA,
    NPC_GIRL,
    NPC_MUSHROOM,
    NPC_BOY,
    NPC_GRANDPA2,
    NPC_SNAIL_JOCKEY,
    NPC_NOME,
    NPC_BOY2,
    NPC_MUSHROOM_EMBLEM_F,
    NPC_DANCING_GRANDMA,
    NPC_DANCING_GRANDMA2,
    NPC_SNAIL_EMBLEM_E,
    NPC_BOY_MUSHROOM_SHOES,
    NPC_GRANDMA,
    NPC_GIRL2,
    NPC_MUSHROOM2,
    NPC_SNAIL_RACER,
    NPC_SNAIL_RACER2,
    NPC_GIRL3,
    NPC_MUSHROOM3,
    NPC_SNAIL,
    NPC_GRANDPA3,
    NPC_SNAIL2,
    NPC_GRANDPA4,
    NPC_GRANDPA_LUNE,
    NPC_GRANDPA5,
    NPC_MOUNTAIN_KING,

    NPC_PLANT_HERB,
    NPC_PLANT,
    NPC_CHEST_OF_DRAWERS_MYSTIC_ARMOR,
    NPC_CAT,
    NPC_GREAT_DOOR_ZANTETSU_SWORD,
    NPC_CAT2,
    NPC_GREAT_DOOR,
    NPC_CAT3,
    NPC_MODEL_TOWN1,
    NPC_GREAT_DOOR_MODEL_TOWNS,
    NPC_STEPS_UPSTAIRS,
    NPC_CAT_DOOR_KEY,
    NPC_MOUSE,
    NPC_MARIE,
    NPC_DOLL,
    NPC_CHEST_OF_DRAWERS,
    NPC_PLANT2,
    NPC_MOUSE2,
    NPC_MOUSE_SPARK_BOMB,
    NPC_MOUSE3,
    NPC_GREAT_DOOR_SOUL_OF_DETECTION,
    NPC_MODEL_TOWN2,
    NPC_MOUSE4,
    NPC_STEPS_MARIE,
    NPC_CHEST_OF_DRAWERS2,
    NPC_PLANT_ACTINIDIA_LEAVES,
    NPC_MOUSE5,
    NPC_CAT4,
    NPC_STAIRS_POWER_PLANT,

    NPC_SOLDIER,
    NPC_SOLDIER2,
    NPC_SOLDIER3,
    NPC_SOLDIER_ELEMENTAL_MAIL,
    NPC_SOLDIER4,
    NPC_SOLDIER5,
    NPC_SINGER_CONCERT_HALL,
    NPC_SOLDIER6,
    NPC_MAID,
    NPC_SOLDIER_LEFT_TOWER,
    NPC_SOLDIER_DOK,
    NPC_SOLDIER_PLATINUM_CARD,
    NPC_SINGER,
    NPC_SOLDIER_SOUL_OF_REALITY,
    NPC_MAID2,
    NPC_QUEEN_MAGRIDD,
    NPC_SOLDIER_WITH_LEO,
    NPC_SOLDIER_RIGHT_TOWER,
    NPC_DR_LEO,
    NPC_SOLDIER7,
    NPC_SOLDIER8,
    NPC_MAID_HERB,
    NPC_SOLDIER_CASTLE,
    NPC_SOLDIER9,
    NPC_SOLDIER10,
    NPC_SOLDIER11,
    NPC_KING_MAGRIDD
};

struct Item {
    bool isNPC;
    bool isProgression;
    bool isRequired;
    bool isEquipment;
    bool isUnique;
    bool isConsumable;
    bool isExperience;
    NpcId npcId;    // aka original Lair offset
    ItemId itemId;
    int ExpAmount;
    char name[ITEM_NAME_MAX_LENGTH];
};

class ItemPool {
public:
    ItemPool();
    ~ItemPool();

    static Item allItems[MAX_POOL_SIZE];
    static int allItemsCount;

    static ItemIndex itemIdMap[256];
    static ItemIndex npcIdMap[NPC_ID_MAX];

    int itemList[MAX_POOL_SIZE];
    void addItem (ItemIndex i);
    void removeItem (ItemIndex i);
    bool hasItem (ItemIndex i);

    static void logAllItems();
    static void logList();

    static void populateItem (ItemIndex i, Item* flags, ItemId id, const char* name);
    static void populateNpc (ItemIndex i, Item* flags, NpcId id, const char* name);
    static void populate ();

    static ItemIndex getItemIndexForItemId (ItemId id);
    static ItemIndex getItemIndexForNpcId (NpcId id);
    static ItemIndex getItemIndexForGemsOrExp (int expAmount);
    static const Item& getItemByIndex (ItemIndex index);
};

void resetFlags (Item &flags);
void logItem (const Item &item);


#endif // __ITEMPOOL_H__
